# Multi-Platform Image Build Pipeline
#
# This pipeline builds images for multiple cloud platforms in parallel,
# tracking each build's state independently through the Build State API.
#
# Features:
# - Parallel builds for AWS, Azure, and GCP
# - Individual state tracking per platform
# - Fan-in pattern for consolidated reporting
# - Reference data lookup and caching
#
# Usage:
#   fly -t <target> set-pipeline -p multi-platform-build \
#     -c multi-platform-build.yml \
#     -v buildstate-api-url=https://api.example.com \
#     -v project-id=<uuid>

resources:
  - name: packer-templates
    type: git
    source:
      uri: https://github.com/your-org/packer-templates.git
      branch: main
  
  # Build trigger - daily at 3 AM
  - name: daily-trigger
    type: time
    source:
      interval: 24h
      start: 3:00 AM
      stop: 4:00 AM

jobs:
  # Initialize reference data (run once, cache results)
  - name: setup-reference-data
    plan:
      - get: packer-templates
        trigger: true
      
      - get: daily-trigger
        trigger: true
      
      - task: cache-reference-data
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: "3.11-slim"
          
          outputs:
            - name: reference-data
          
          params:
            BLDST_API_URL: ((buildstate-api-url))
            BLDST_API_KEY: ((buildstate-api-key))
          
          run:
            path: sh
            args:
              - -exc
              - |
                # Install CLI
                pip3 install --quiet buildstate-cli
                bldst config set-url "$BLDST_API_URL"
                bldst auth set-key "$BLDST_API_KEY"
                
                # Fetch and cache reference data as JSON
                bldst platform list --output json > reference-data/platforms.json
                bldst os-version list --output json > reference-data/os-versions.json
                bldst image-type list --output json > reference-data/image-types.json
                
                echo "Reference data cached:"
                echo "  Platforms: $(jq length reference-data/platforms.json)"
                echo "  OS Versions: $(jq length reference-data/os-versions.json)"
                echo "  Image Types: $(jq length reference-data/image-types.json)"

  # Build for AWS
  - name: build-aws
    plan:
      - in_parallel:
          - get: packer-templates
            passed: [setup-reference-data]
            trigger: true
          - get: reference-data
            passed: [setup-reference-data]
      
      # Initialize AWS build
      - task: init-aws-build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: "3.11-slim"
          
          inputs:
            - name: reference-data
          
          outputs:
            - name: aws-build-info
          
          params:
            BLDST_API_URL: ((buildstate-api-url))
            BLDST_API_KEY: ((buildstate-api-key))
            PROJECT_ID: ((project-id))
            PLATFORM: "aws-commercial"
            OS_VERSION: "rhel-8.10"
            IMAGE_TYPE: "base"
          
          run:
            path: sh
            args:
              - -exc
              - |
                pip3 install --quiet buildstate-cli
                bldst config set-url "$BLDST_API_URL"
                bldst auth set-key "$BLDST_API_KEY"
                
                # Lookup reference data from cache
                PLATFORM_UUID=$(jq -r ".[] | select(.name==\"$PLATFORM\") | .id" reference-data/platforms.json)
                OS_UUID=$(jq -r ".[] | select(.version==\"$OS_VERSION\") | .id" reference-data/os-versions.json)
                IMAGE_TYPE_UUID=$(jq -r ".[] | select(.name==\"$IMAGE_TYPE\") | .id" reference-data/image-types.json)
                
                # Create build
                BUILD_UUID=$(bldst build create \
                  --build-number "aws-rhel8-$BUILD_ID" \
                  --project-id "$PROJECT_ID" \
                  --platform-id "$PLATFORM_UUID" \
                  --os-version-id "$OS_UUID" \
                  --image-type-id "$IMAGE_TYPE_UUID" \
                  --created-by "concourse" \
                  --output json | jq -r '.id')
                
                echo "$BUILD_UUID" > aws-build-info/uuid.txt
                echo "AWS Build initialized: $BUILD_UUID"
      
      # Run Packer for AWS
      - task: packer-build-aws
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: your-registry/packer-builder
              tag: latest
          
          inputs:
            - name: packer-templates
            - name: aws-build-info
          
          outputs:
            - name: aws-artifacts
          
          params:
            BLDST_API_URL: ((buildstate-api-url))
            BLDST_API_KEY: ((buildstate-api-key))
            AWS_ACCESS_KEY_ID: ((aws.access_key))
            AWS_SECRET_ACCESS_KEY: ((aws.secret_key))
          
          run:
            path: sh
            args:
              - -exc
              - |
                BUILD_UUID=$(cat aws-build-info/uuid.txt)
                
                # Configure CLI
                bldst config set-url "$BLDST_API_URL"
                bldst auth set-key "$BLDST_API_KEY"
                
                # Update state
                bldst build add-state "$BUILD_UUID" --state 25 --status "Starting AWS Packer build"
                
                # Run Packer
                cd packer-templates
                packer build \
                  -var "build_uuid=$BUILD_UUID" \
                  -var "bldst_api_url=$BLDST_API_URL" \
                  -var "bldst_api_key=$BLDST_API_KEY" \
                  -var "cloud_provider=aws" \
                  multi-cloud-rhel8.pkr.hcl
                
                # Save AMI ID
                AMI_ID=$(jq -r '.builds[0].artifact_id' manifest.json | cut -d: -f2)
                echo "$AMI_ID" > ../aws-artifacts/image-id.txt
                
                # Complete
                bldst build add-state "$BUILD_UUID" --state 100 --status "AWS build complete: $AMI_ID"

  # Build for Azure (parallel with AWS)
  - name: build-azure
    plan:
      - in_parallel:
          - get: packer-templates
            passed: [setup-reference-data]
            trigger: true
          - get: reference-data
            passed: [setup-reference-data]
      
      - task: init-azure-build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: "3.11-slim"
          
          inputs:
            - name: reference-data
          
          outputs:
            - name: azure-build-info
          
          params:
            BLDST_API_URL: ((buildstate-api-url))
            BLDST_API_KEY: ((buildstate-api-key))
            PROJECT_ID: ((project-id))
            PLATFORM: "azure-commercial"
            OS_VERSION: "rhel-8.10"
            IMAGE_TYPE: "base"
          
          run:
            path: sh
            args:
              - -exc
              - |
                pip3 install --quiet buildstate-cli
                bldst config set-url "$BLDST_API_URL"
                bldst auth set-key "$BLDST_API_KEY"
                
                PLATFORM_UUID=$(jq -r ".[] | select(.name==\"$PLATFORM\") | .id" reference-data/platforms.json)
                OS_UUID=$(jq -r ".[] | select(.version==\"$OS_VERSION\") | .id" reference-data/os-versions.json)
                IMAGE_TYPE_UUID=$(jq -r ".[] | select(.name==\"$IMAGE_TYPE\") | .id" reference-data/image-types.json)
                
                BUILD_UUID=$(bldst build create \
                  --build-number "azure-rhel8-$BUILD_ID" \
                  --project-id "$PROJECT_ID" \
                  --platform-id "$PLATFORM_UUID" \
                  --os-version-id "$OS_UUID" \
                  --image-type-id "$IMAGE_TYPE_UUID" \
                  --created-by "concourse" \
                  --output json | jq -r '.id')
                
                echo "$BUILD_UUID" > azure-build-info/uuid.txt
                echo "Azure Build initialized: $BUILD_UUID"
      
      - task: packer-build-azure
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: your-registry/packer-builder
              tag: latest
          
          inputs:
            - name: packer-templates
            - name: azure-build-info
          
          outputs:
            - name: azure-artifacts
          
          params:
            BLDST_API_URL: ((buildstate-api-url))
            BLDST_API_KEY: ((buildstate-api-key))
            AZURE_CLIENT_ID: ((azure.client_id))
            AZURE_CLIENT_SECRET: ((azure.client_secret))
            AZURE_SUBSCRIPTION_ID: ((azure.subscription_id))
            AZURE_TENANT_ID: ((azure.tenant_id))
          
          run:
            path: sh
            args:
              - -exc
              - |
                BUILD_UUID=$(cat azure-build-info/uuid.txt)
                bldst config set-url "$BLDST_API_URL"
                bldst auth set-key "$BLDST_API_KEY"
                
                bldst build add-state "$BUILD_UUID" --state 25 --status "Starting Azure Packer build"
                
                cd packer-templates
                packer build \
                  -var "build_uuid=$BUILD_UUID" \
                  -var "bldst_api_url=$BLDST_API_URL" \
                  -var "bldst_api_key=$BLDST_API_KEY" \
                  -var "cloud_provider=azure" \
                  multi-cloud-rhel8.pkr.hcl
                
                IMAGE_ID=$(jq -r '.builds[0].artifact_id' manifest.json)
                echo "$IMAGE_ID" > ../azure-artifacts/image-id.txt
                
                bldst build add-state "$BUILD_UUID" --state 100 --status "Azure build complete: $IMAGE_ID"

  # Build for GCP (parallel with AWS and Azure)
  - name: build-gcp
    plan:
      - in_parallel:
          - get: packer-templates
            passed: [setup-reference-data]
            trigger: true
          - get: reference-data
            passed: [setup-reference-data]
      
      - task: init-gcp-build
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: "3.11-slim"
          
          inputs:
            - name: reference-data
          
          outputs:
            - name: gcp-build-info
          
          params:
            BLDST_API_URL: ((buildstate-api-url))
            BLDST_API_KEY: ((buildstate-api-key))
            PROJECT_ID: ((project-id))
            PLATFORM: "gcp"
            OS_VERSION: "rhel-8.10"
            IMAGE_TYPE: "base"
          
          run:
            path: sh
            args:
              - -exc
              - |
                pip3 install --quiet buildstate-cli
                bldst config set-url "$BLDST_API_URL"
                bldst auth set-key "$BLDST_API_KEY"
                
                PLATFORM_UUID=$(jq -r ".[] | select(.name==\"$PLATFORM\") | .id" reference-data/platforms.json)
                OS_UUID=$(jq -r ".[] | select(.version==\"$OS_VERSION\") | .id" reference-data/os-versions.json)
                IMAGE_TYPE_UUID=$(jq -r ".[] | select(.name==\"$IMAGE_TYPE\") | .id" reference-data/image-types.json)
                
                BUILD_UUID=$(bldst build create \
                  --build-number "gcp-rhel8-$BUILD_ID" \
                  --project-id "$PROJECT_ID" \
                  --platform-id "$PLATFORM_UUID" \
                  --os-version-id "$OS_UUID" \
                  --image-type-id "$IMAGE_TYPE_UUID" \
                  --created-by "concourse" \
                  --output json | jq -r '.id')
                
                echo "$BUILD_UUID" > gcp-build-info/uuid.txt
                echo "GCP Build initialized: $BUILD_UUID"
      
      - task: packer-build-gcp
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: your-registry/packer-builder
              tag: latest
          
          inputs:
            - name: packer-templates
            - name: gcp-build-info
          
          outputs:
            - name: gcp-artifacts
          
          params:
            BLDST_API_URL: ((buildstate-api-url))
            BLDST_API_KEY: ((buildstate-api-key))
            GCP_PROJECT_ID: ((gcp.project_id))
            GOOGLE_APPLICATION_CREDENTIALS: ((gcp.service_account_json))
          
          run:
            path: sh
            args:
              - -exc
              - |
                BUILD_UUID=$(cat gcp-build-info/uuid.txt)
                bldst config set-url "$BLDST_API_URL"
                bldst auth set-key "$BLDST_API_KEY"
                
                bldst build add-state "$BUILD_UUID" --state 25 --status "Starting GCP Packer build"
                
                # Write service account JSON
                echo "$GOOGLE_APPLICATION_CREDENTIALS" > /tmp/gcp-credentials.json
                export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-credentials.json
                
                cd packer-templates
                packer build \
                  -var "build_uuid=$BUILD_UUID" \
                  -var "bldst_api_url=$BLDST_API_URL" \
                  -var "bldst_api_key=$BLDST_API_KEY" \
                  -var "cloud_provider=gcp" \
                  multi-cloud-rhel8.pkr.hcl
                
                IMAGE_ID=$(jq -r '.builds[0].artifact_id' manifest.json)
                echo "$IMAGE_ID" > ../gcp-artifacts/image-id.txt
                
                bldst build add-state "$BUILD_UUID" --state 100 --status "GCP build complete: $IMAGE_ID"

  # Consolidate results from all platforms
  - name: report-results
    plan:
      - in_parallel:
          - get: aws-artifacts
            passed: [build-aws]
            trigger: true
          - get: azure-artifacts
            passed: [build-azure]
            trigger: true
          - get: gcp-artifacts
            passed: [build-gcp]
            trigger: true
          - get: aws-build-info
            passed: [build-aws]
          - get: azure-build-info
            passed: [build-azure]
          - get: gcp-build-info
            passed: [build-gcp]
      
      - task: generate-report
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: python
              tag: "3.11-slim"
          
          inputs:
            - name: aws-artifacts
            - name: azure-artifacts
            - name: gcp-artifacts
            - name: aws-build-info
            - name: azure-build-info
            - name: gcp-build-info
          
          params:
            BLDST_API_URL: ((buildstate-api-url))
            BLDST_API_KEY: ((buildstate-api-key))
          
          run:
            path: sh
            args:
              - -exc
              - |
                pip3 install --quiet buildstate-cli
                bldst config set-url "$BLDST_API_URL"
                bldst auth set-key "$BLDST_API_KEY"
                
                echo "========================================="
                echo "Multi-Platform Build Summary"
                echo "========================================="
                echo ""
                
                # AWS
                AWS_UUID=$(cat aws-build-info/uuid.txt)
                AWS_IMAGE=$(cat aws-artifacts/image-id.txt)
                echo "AWS Build:"
                echo "  Build UUID: $AWS_UUID"
                echo "  AMI ID: $AWS_IMAGE"
                bldst build get "$AWS_UUID" --output json | jq -r '.current_state'
                echo ""
                
                # Azure
                AZURE_UUID=$(cat azure-build-info/uuid.txt)
                AZURE_IMAGE=$(cat azure-artifacts/image-id.txt)
                echo "Azure Build:"
                echo "  Build UUID: $AZURE_UUID"
                echo "  Image ID: $AZURE_IMAGE"
                bldst build get "$AZURE_UUID" --output json | jq -r '.current_state'
                echo ""
                
                # GCP
                GCP_UUID=$(cat gcp-build-info/uuid.txt)
                GCP_IMAGE=$(cat gcp-artifacts/image-id.txt)
                echo "GCP Build:"
                echo "  Build UUID: $GCP_UUID"
                echo "  Image ID: $GCP_IMAGE"
                bldst build get "$GCP_UUID" --output json | jq -r '.current_state'
                echo ""
                
                echo "========================================="
                echo "All builds completed successfully!"
                echo "========================================="
